name: Docker

on:
  push:
    branches: [ "main" ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # - name: Build
      #   run: docker compose build

      - name: Obter última versão
        id: get_latest_version
        run: |
          latest_version=$(curl --silent "https://api.github.com/repos/PAlucas/trab1/releases/latest" | grep -Po '"tag_name":\s*"\K[^"]+')
          echo "::set-output name=latest_version::$latest_version"

      - name: Exibir última versão
        run: |
          echo "A última versão do repositório é ${{ steps.get_latest_version.outputs.latest_version }}"

      # - name: tag
      #   run: |
      #     docker tag nginx-trab ${{ env.REGISTRY }}/palucas/nginx-trab:${{ steps.get_latest_version.outputs.latest_version }}
          
      #     docker tag front ${{ env.REGISTRY }}/palucas/front:${{ steps.get_latest_version.outputs.latest_version }}

      #     docker tag back ${{ env.REGISTRY }}/palucas/back:${{ steps.get_latest_version.outputs.latest_version }}

      # - name: Log into registry ghcr.io
      #   uses: docker/login-action@v1
      #   with:
      #     registry: ${{ env.REGISTRY }}
      #     username: PAlucas
      #     password: ${{ secrets.GITHUB_TOKEN }}

      # - name: push
      #   run: |
      #     docker push  ${{ env.REGISTRY }}/palucas/nginx-trab:${{ steps.get_latest_version.outputs.latest_version }}

      #     docker push  ${{ env.REGISTRY }}/palucas/front:${{ steps.get_latest_version.outputs.latest_version }}

      #     docker push  ${{ env.REGISTRY }}/palucas/back:${{ steps.get_latest_version.outputs.latest_version }}
      