name: Docker

on:
  push:
    branches: [ "main" ]
    tags: [ 'v*.*.*' ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  IMAGE_TAG: ${{ steps.meta.outputs.tags }} 

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build
        run: docker compose build

      - name: tag
        run: |
          docker tag nginx-trab ${{ env.REGISTRY }}/palucas/nginx-trab:${{ env.IMAGE_TAG }}
          
          docker tag front ${{ env.REGISTRY }}/palucas/front:${{ env.IMAGE_TAG }}

          docker tag back ${{ env.REGISTRY }}/palucas/back:${{ env.IMAGE_TAG }}

      - name: Log into registry ghcr.io
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: PAlucas
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: push
        run: |
          docker push  ${{ env.REGISTRY }}/palucas/nginx-trab:${{ env.IMAGE_TAG }}

          docker push  ${{ env.REGISTRY }}/palucas/front:${{ env.IMAGE_TAG }}

          docker push  ${{ env.REGISTRY }}/palucas/back:${{ env.IMAGE_TAG }}
      