name: Github CI
on:
  # Configura servidor de CI para executar o pipeline de tarefas abaixo (jobs) quando 
  # um push ou pull request for realizado tendo como alvo a branch main
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  pipeline:
    runs-on: ubuntu-latest # Os comandos serão executados em um sistema operacional Linux

    steps:
      - name: Git Checkout
        uses: actions/checkout@v2 # Faz o checkout do código recebido

      - name: Create Network
        run: docker network create trab-1 --driver=bridge

      - name: Build
        run: docker compose build

      - name: run
        run: |
          docker-compose up -d db
          command-1

          docker-compose up -d back-end
          command-2

          docker-compose up -d frontend
          command-3

          docker-compose up -d proxy
          command-4



